version: '3.4'

services:
  api:
    container_name: JwTDemoApp
    build: ./
    ports:
      - '5001:5001'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password@123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ./src/https/aspnetapp.pfx:/https/aspnetapp.pfx:ro
    restart: always